package Formularios;
import Entidades.*;
import Negocio.*;
import javax.swing.table.DefaultTableModel;
import static com.wagnerandade.coollection.Coollection.*;
import com.wagnerandade.coollection.query.order.Order;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.StringTokenizer;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
/**
 *
 * @author Nicolas Martinez Ullan - 66947 - AED - Trabajo Investigacion -
 * Noviembre 2014
 */
public class FormularioCurso extends javax.swing.JFrame {
    private DefaultTableModel modeloCursos;
    private final NegocioCurso negocioCurso = new NegocioCurso();
    public FormularioCurso() {
        initComponents();
        configurarFormulario();
        cargarTablaCursos();
        cargarComboBoxCarreras();
        cargarComboBoxNiveles();
        reiniciarFormatoFormulario();
    }

    private void configurarFormulario(){
        modeloCursos = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        modeloCursos.setColumnIdentifiers(new Object[]{ "Nivel", "Carrera", "Numero", "CursoId", "NivelId", "CarreraId" });
        cboCarreras.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Object item = value;
                // if the item to be rendered is Proveedores then display it's Name
                if (item instanceof Carrera)
                    item = ((Carrera) item).toString();
                return super.getListCellRendererComponent(list, item, index, isSelected, cellHasFocus);
            }
        });
        cboNiveles.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Object item = value;
                if (item instanceof Nivel)
                    item = ((Nivel) item).getNivel();
                return super.getListCellRendererComponent(list, item, index, isSelected, cellHasFocus);
            }
        });
    }
    
    private void reiniciarFormatoFormulario(){
        tfNumero.setText("");
        cboCarreras.setSelectedIndex(-1);
        cboNiveles.setSelectedIndex(-1);
        cboNiveles.requestFocus();
    }
    
    private void cargarComboBoxNiveles() {
        from(Repositorio.getNiveles()).orderBy("getNivel", Order.ASC).all().forEach(n -> cboNiveles.addItem(n));
    }

    private void cargarComboBoxCarreras() {
        from(Repositorio.getCarreras()).orderBy("getCodigo", Order.ASC).all().forEach(c -> cboCarreras.addItem(c));
    }

    private void limpiarModeloTabla(){
        while (modeloCursos.getRowCount()>0) 
            modeloCursos.removeRow(0);
    }
    
    private void cargarTablaCursos() {
        limpiarModeloTabla();
        Repositorio.getCursos().forEach(c -> {
            modeloCursos.addRow(new Object[]{
                    from(Repositorio.getNiveles()).where("getNivelId", eq(c.getNivelId())).first().getNivel()
                    , from(Repositorio.getCarreras()).where("getCarreraId", eq(c.getCarreraId())).first().toString()
                    , c.getNumero()
                    , c.getCursoId()
                    , from(Repositorio.getNiveles()).where("getNivelId", eq(c.getNivelId())).first().getNivelId()
                    , from(Repositorio.getCarreras()).where("getCarreraId", eq(c.getCarreraId())).first().getCarreraId()
            });
        });
        tblCursos.setModel(modeloCursos);
        StringTokenizer st = new StringTokenizer("CursoId;CarreraId;NivelId", ";");
        while (st.hasMoreElements()) {
            try {
                String t = st.nextToken();
                tblCursos.removeColumn(tblCursos.getColumn(t));
            }
            catch (Exception e) {
            }
        }
//        if(tblCursos.getColumn("CursoId") != null)
//            tblCursos.removeColumn(tblCursos.getColumn("CursoId"));
//        if(tblCursos.getColumn("CarreraId") != null)
//            tblCursos.removeColumn(tblCursos.getColumn("CarreraId"));
//        if(tblCursos.getColumn("NivelId") != null)
//            tblCursos.removeColumn(tblCursos.getColumn("NivelId"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        cboCarreras = new javax.swing.JComboBox();
        cboNiveles = new javax.swing.JComboBox();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfPrevisualizacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cursos");

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nivel", "Carrera", "Número"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCursos);

        lblNombre.setText("Número");

        lblCarrera.setText("Carrera");

        lblNivel.setText("Nivel");

        tfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumeroFocusLost(evt);
            }
        });
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNumeroKeyPressed(evt);
            }
        });

        cboCarreras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboCarrerasFocusLost(evt);
            }
        });
        cboCarreras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCarrerasKeyPressed(evt);
            }
        });

        cboNiveles.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboNivelesFocusLost(evt);
            }
        });
        cboNiveles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboNivelesKeyPressed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMensaje.setToolTipText("");

        jLabel1.setText("Previsualización");

        tfPrevisualizacion.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCarrera)
                                    .addComponent(lblNivel)
                                    .addComponent(jLabel1))
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPrevisualizacion)
                                    .addComponent(tfNumero)
                                    .addComponent(cboCarreras, 0, 237, Short.MAX_VALUE)
                                    .addComponent(cboNiveles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(cboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPrevisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar)
                    .addComponent(btnRefrescar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        cboNiveles.setSelectedIndex(-1);
        cboNiveles.requestFocus();
        cboCarreras.setSelectedIndex(-1);
        tfNumero.setText("");
        tfPrevisualizacion.setText("");
        btnEliminar.setEnabled(false);
        btnRefrescar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed
    private void armarPrevisualizacion(){
        String nivel = "";
        String codigoCarrera = "";
        
        if (cboNiveles.getSelectedIndex() > -1)
            nivel = ((Nivel)cboNiveles.getSelectedItem()).getNivel().toString();
        if (cboCarreras.getSelectedIndex() > -1)
            codigoCarrera = ((Carrera)cboCarreras.getSelectedItem()).getCodigo();
        tfPrevisualizacion.setText(
                nivel
                + codigoCarrera
                + tfNumero.getText().trim().toUpperCase()
        );
    }
    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblCursos.getModel();
        tfNumero.setText(model.getValueAt(tblCursos.getSelectedRow(), model.findColumn("Numero")).toString());
        int carreraId = Integer.parseInt(model.getValueAt(tblCursos.getSelectedRow(), model.findColumn("CarreraId")).toString());
        int nivelId = Integer.parseInt(model.getValueAt(tblCursos.getSelectedRow(), model.findColumn("NivelId")).toString());
        cboCarreras.setSelectedItem(from(Repositorio.getCarreras()).where("getCarreraId", eq(carreraId)).first());
        cboNiveles.setSelectedItem(from(Repositorio.getNiveles()).where("getNivelId", eq(nivelId)).first());
        armarPrevisualizacion();
    }//GEN-LAST:event_tblCursosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void mensajeExito(String mensaje){
        lblMensaje.setText(mensaje);
        lblMensaje.setForeground(new Color(0, 153, 0));
    }
    private void mensajeError(String mensaje){
        lblMensaje.setText(mensaje);
        lblMensaje.setForeground(Color.RED);
    }
    private void guardar(){
        if (cboNiveles.getSelectedIndex()==-1) {
            mensajeError("Debe seleccionar un nivel.");
            cboNiveles.requestFocus();
            return;
        }
        if (cboCarreras.getSelectedIndex()==-1) {
            mensajeError("Debe seleccionar una carrera.");
            cboCarreras.requestFocus();
            return;
        }
        if (tfNumero.getText().trim().equals("")) {
            mensajeError("Debe ingresar un nombre.");
            tfNumero.requestFocus();
            return;
        }
        boolean esPosibleAgregar = negocioCurso.insertar(
                ((Nivel)cboNiveles.getSelectedItem()).getNivelId()
                , ((Carrera)cboCarreras.getSelectedItem()).getCarreraId()
                , Integer.parseInt(tfNumero.getText().trim()));
        if (esPosibleAgregar) {
            mensajeExito("Curso agregado exitosamente.");
            reiniciarFormatoFormulario();
        }
        else{
            mensajeError("No se pudo agregar curso.\nVerifique que la combinacion de nivel-carrera-numero.");
            cboNiveles.requestFocus();
        }
        Repositorio.refrescarCursos();
        cargarTablaCursos();
    }
    
    private void tfNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusGained
        tfNumero.selectAll();
    }//GEN-LAST:event_tfNumeroFocusGained

    private void tfNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_tfNumeroKeyPressed

    private void cboCarrerasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCarrerasKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_cboCarrerasKeyPressed

    private void cboNivelesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboNivelesKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_cboNivelesKeyPressed

    private void cboNivelesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboNivelesFocusLost
        armarPrevisualizacion();
    }//GEN-LAST:event_cboNivelesFocusLost

    private void cboCarrerasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboCarrerasFocusLost
        armarPrevisualizacion();
    }//GEN-LAST:event_cboCarrerasFocusLost

    private void tfNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusLost
        armarPrevisualizacion();
    }//GEN-LAST:event_tfNumeroFocusLost

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblCursos.getSelectedRow() == -1) {
            mensajeError("Debe seleccionar un curso.");
            return;
        }
        int cursoId = Integer.parseInt(tblCursos.getValueAt(tblCursos.getSelectedRow(), modeloCursos.findColumn("CursoId")).toString());
//        boolean borradoExitoso = negocioCurso.eliminar(cursoId);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox cboCarreras;
    private javax.swing.JComboBox cboNiveles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPrevisualizacion;
    // End of variables declaration//GEN-END:variables
}
